//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCache {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetCache.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} not support multiple key operation 的本地化字符串。
        /// </summary>
        internal static string Not_Support_Multiple_Key_Opration {
            get {
                return ResourceManager.GetString("Not_Support_Multiple_Key_Opration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output length({0}) not equals input length({1}) 的本地化字符串。
        /// </summary>
        internal static string Output_Length_Not_Match_Input_Length {
            get {
                return ResourceManager.GetString("Output_Length_Not_Match_Input_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please don&apos;t repeat Wait before Release 的本地化字符串。
        /// </summary>
        internal static string Repeat_Wait {
            get {
                return ResourceManager.GetString("Repeat_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not support Task 的本地化字符串。
        /// </summary>
        internal static string Serializer_Not_Support_Task {
            get {
                return ResourceManager.GetString("Serializer_Not_Support_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for lock timeout. 的本地化字符串。
        /// </summary>
        internal static string Wait_Lock_Timeout {
            get {
                return ResourceManager.GetString("Wait_Lock_Timeout", resourceCulture);
            }
        }
    }
}
